# This file contains aliases to be sourced from .bashrc or .zshrc

# Enable color support for some commands.
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    if [ -x /usr/bin/dircolors ]; then
            # enable color support of ls and also add handy aliases
        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
        alias ls='ls --color=auto'
        alias dir='dir --color=auto'
        alias vdir='vdir --color=auto'

        alias grep='grep --color=auto'
        alias fgrep='fgrep --color=auto'
        alias egrep='egrep --color=auto'
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    alias ls='ls -G'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# use neovim not vim
alias vim=nvim

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Useful personal bash aliases.

alias sl='ls' # So I can just mash sl/ls and not worry about the order in which I pressed them.
alias cd..='cd ..' # Because I always do this.
alias pdw='pwd' # and this...
alias t=tmux # Launch tmux more quickly.
alias v=nvim # Launch vim more quickly.
alias vi=nvim # Don't ever use vi
alias vom=nvim # Typo..
alias nonja=ninja # As above...
alias gerp=grep # ...
alias h=history # Quicker history access.

# Git shortcuts
alias stash='git stash'
alias show='git show'

# vim like exit commands.
alias :q='exit'

# Draw a red line accross the terminal
alias line='numcols=$(tput cols);echo -ne "\033[0;31m╠"; printf "%0.s═" {1..$(( numcols - 3 ))}; echo -ne "╣\033[0m \n";'
