# Useful personal bash aliases.

alias sl='ls' # So I can just mash sl/ls and not worry about the order in which I pressed them.
alias cd..='cd ..' # Because I always do this.
alias t=tmux # Launch tmux more quickly.
alias v=vim # Launch vim more quickly.
alias h=history # Quicker history access.
